* Coding Gamification

** NEXT ACTION

- [x] fetch all data for a repo
- [x] fix prs count, it is always 0 now
- [x] compute project health
- [ ] design matchmaking and mmr

** Project Health

What is winning?

Winning is determined by *Project Health*.

- Stars / Forks (user feedback)
- Pick "random", important, hidden Issues, PRs and look how long it takes the project to fix them
- releases (should be somewhat frequent)

** MMR

- both global leaderboard rank and 1v1 MMR
- matchmaking like in league or clashofclans

** Battle Time

- constant lop of everything / actions going on in both repos
- all chat for "friendly" banter
- voting from community, maybe the dude who opened the issue / pr
- top player -> mid player -> last player (rookie)

** Misc Ideas

- fixed team size: 1v1, 3v3, 5v5, 10v10; but not more than 10, the project should send only their best
- dev setup information (as tags maybe) for each member (optional)
- streaks / combos ?!
- repo can use "protection" (for holidays, to avoid battle / being attacked)
- battle period ~1 month

** Battle Outcome Evaluation

- MMR calculation (maybe archievements, rewards)
- leaderboard updates
- top contributors
- history / everything recorded forever
- post battle winner and loser have a "cooldown" period

** 2026-02-27 Notes

- battle uses the CoC system -> you choose to attack an opponent projects with similar HP (system shows you a few options)
- we need ONLY HP as a metric for deciding the winner: A is 80HP, B is 75HP => END: A is 80HP, B is 79HP -> A won. Maintaining rank 1 is hard!
- we want an exciting battle, when we can lose / attack HP. The idea is, that it applies a HP debuff, and you clearly see, absolute HP vs. debuff (castle destroyed)
- the debuff can be removed / healed (castle repaired) by: waiting (small amount/time), active repair (working on project), help from other project? (healing), winning a battle?
- projects and repos should have a MORALE in addition to HP, which shows the "team spirit" / "vibes" of the project
- this MORALE can decide a lot of things and act as sugar, better recovery, better spot on leaderboard, a fire icon next to project, etc.
- in battle we need RNG, very small, but still and bit of spice to get the crowd going!
-
